#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 VERHILLE Arnaud
# Élément de démarrage : charge POMPPCFsqrt.kext (kHasFsqrt dans la commpage, la
# libm prend `fsqrt`). Un kext sans personnalité IOKit n'est pas chargé seul.

. /etc/rc.common

StartService ()
{
    ConsoleMessage "POMPPC : fsqrt annoncé"
    kextload /System/Library/Extensions/POMPPCFsqrt.kext
}

StopService ()
{
    kextunload -b net.pomppc.POMPPCFsqrt
}

RestartService ()
{
    StopService
    StartService
}

RunService "$1"
